import pathlib
base = pathlib.Path(r'F:\Program_data\pycharm_data\MyDesktop\desktop-pet\pet')
app_path = base / 'app.py'
states_path = base / 'states.py'
renderer_path = base / 'renderer.py'
app_text = app_path.read_text(encoding='utf-8')
states_text = states_path.read_text(encoding='utf-8')
renderer_text = renderer_path.read_text(encoding='utf-8')
states_text = states_text.replace(
    'class PetState(str, Enum):\n    IDLE = "idle"\n    HAPPY = "happy"\n    WAVING = "waving"\n    EATING = "eating"\n    SLEEPING = "sleeping"\n    SAD = "sad"\n    BUSY = "busy"\n    DRAG = "drag"\n    SPEAKING = "speaking"\n',
    'class PetState(str, Enum):\n    IDLE = "idle"\n    HAPPY = "happy"\n    WAVING = "waving"\n    EATING = "eating"\n    SLEEPING = "sleeping"\n    SAD = "sad"\n    BUSY = "busy"\n    DRAG = "drag"\n    SPEAKING = "speaking"\n    MOVING_LEFT = "moving_left"\n    MOVING_RIGHT = "moving_right"\n    MOVING_UP = "moving_up"\n    MOVING_DOWN = "moving_down"\n'
)
states_text = states_text.replace('    PetState.SPEAKING: [150, 150, 150, 280],\n', '    PetState.SPEAKING: [150, 150, 150, 280],\n    PetState.MOVING_LEFT: [90, 90, 90],\n    PetState.MOVING_RIGHT: [90, 90, 90],\n    PetState.MOVING_UP: [90, 90, 90],\n    PetState.MOVING_DOWN: [90, 90, 90],\n')
states_path.write_text(states_text, encoding='utf-8')
renderer_text = renderer_text.replace('class Renderer:\n    def __init__(self, canvas: tk.Canvas, cfg: PetConfig, sheet: Spritesheet | None) -> None:', 'class Renderer:\n    def __init__(self, canvas: tk.Canvas, cfg: PetConfig, sheet: Spritesheet | None, moving_states: dict[tuple[int, int], PetState] | None = None) -> None:')
renderer_text = renderer_text.replace('        self.sheet = sheet\n        self._image_item: int | None = None\n        self._last_state: PetState | None = None', '        self.sheet = sheet\n        self.moving_states = moving_states or {}\n        self._image_item: int | None = None\n        self._last_state: PetState | None = None')
renderer_text = renderer_text.replace('        if state == PetState.DRAG:\n            self._motion_lines(cx - rx, cy + ry * 0.4)\n', '        if state == PetState.DRAG:\n            self._motion_lines(cx - rx, cy + ry * 0.4)\n\n        if state in (PetState.MOVING_LEFT, PetState.MOVING_RIGHT, PetState.MOVING_UP, PetState.MOVING_DOWN):\n            self._draw_moving_placeholder(state, cx, cy, rx, ry)\n')
renderer_path.write_text(renderer_text, encoding='utf-8')
app_text = app_text.replace('        self._selected = False\n', '        self._selected = True\n')
app_text = app_text.replace('        self._move_direction = (0, 0)\n        self._drag_start_pos = (0, 0)\n', '        self._move_direction = (0, 0)\n        self._active_move_key = None\n        self._drag_start_pos = (0, 0)\n')
app_text = app_text.replace('root.bind("<KeyPress>", self._on_key_press)\n        root.bind("<KeyRelease>", self._on_key_release)\n        root.focus_set()\n', 'root.bind("<KeyPress>", self._on_key_press)\n        root.bind("<KeyRelease>", self._on_key_release)\n        root.after(120, lambda: self._ensure_selected(now=time.time()))\n')
app_text = app_text.replace('    def _on_key_press(self, event: tk.Event) -> None:\n        if not self._selected:\n            return\n        key = event.keysym\n', '    def _on_key_press(self, event: tk.Event) -> None:\n        self._ensure_selected(now=time.time())\n        key = event.keysym\n')
for key, direction in [('KP_Up', (0, -1)), ('Up', (0, -1)), ('KP_Down', (0, 1)), ('Down', (0, 1)), ('KP_Left', (-1, 0)), ('Left', (-1, 0)), ('KP_Right', (1, 0)), ('Right', (1, 0)), ('KP_Home', (-1, -1)), ('KP_Prior', (1, -1)), ('KP_End', (-1, 1)), ('KP_Next', (1, 1))]:
    app_text = app_text.replace(f'            self._move_direction = {direction}\n', f'            self._move_direction = {direction}\n            self._active_move_key = key\n')
app_text = app_text.replace('        elif key == "KP_Begin":\n            self._move_direction = (0, 0)\n', '        elif key == "KP_Begin":\n            self._move_direction = (0, 0)\n            self._active_move_key = None\n')
app_text = app_text.replace('    def _on_key_release(self, event: tk.Event) -> None:\n        key = event.keysym\n        if key in ("KP_Up", "Up", "KP_Down", "Down", "KP_Left", "Left", "KP_Right", "Right",\n                   "KP_Home", "KP_Prior", "KP_End", "KP_Next", "KP_Begin"):\n            self._move_direction = (0, 0)\n            if not self._is_random_moving and not self._sleeping and not self._dragged:\n                self.animator.play(PetState.IDLE, loop=True, now=time.time())\n', '    def _on_key_release(self, event: tk.Event) -> None:\n        key = event.keysym\n        if key in ("KP_Up", "Up", "KP_Down", "Down", "KP_Left", "Left", "KP_Right", "Right",\n                   "KP_Home", "KP_Prior", "KP_End", "KP_Next", "KP_Begin"):\n            if self._active_move_key == key:\n                self._active_move_key = None\n            if not self._is_random_moving and not self._sleeping and not self._dragged:\n                self.animator.play(PetState.IDLE, loop=True, now=time.time())\n')
app_text = app_text.replace('    def _handle_movement(self, now: float) -> None:\n        if self._selected and (self._move_direction[0] != 0 or self._move_direction[1] != 0):\n            dx, dy = self._move_direction\n            self._move_pet(dx * self._move_speed, dy * self._move_speed)\n            self._update_move_animation(dx, dy)\n', '    def _handle_movement(self, now: float) -> None:\n        if self._move_direction[0] != 0 or self._move_direction[1] != 0:\n            dx, dy = self._move_direction\n            self._move_pet(dx * self._move_speed, dy * self._move_speed)\n            self._update_move_animation(dx, dy)\n')
app_text = app_text.replace('    def _start_random_move(self, now: float) -> None:\n        self._is_random_moving = True\n        self._random_move_end = now + self._random_move_duration\n        self._move_direction = (random.choice([-1, 0, 1]), random.choice([-1, 0, 1]))\n        while self._move_direction == (0, 0):\n            self._move_direction = (random.choice([-1, 0, 1]), random.choice([-1, 0, 1]))\n        self._update_move_animation(self._move_direction[0], self._move_direction[1])\n        self._last_random_move = now\n', '    def _start_random_move(self, now: float) -> None:\n        self._is_random_moving = True\n        self._random_move_end = now + self._random_move_duration\n        directions = [(-1, 0), (1, 0), (0, -1), (0, 1)]\n        self._move_direction = random.choice(directions)\n        self._update_move_animation(self._move_direction[0], self._move_direction[1])\n        self._last_random_move = now\n')
app_text = app_text.replace(
    '    def _update_move_animation(self, dx: int, dy: int) -> None:\n        if self._sleeping or self._dragged:\n            return\n        if dx > 0 and dy == 0:\n            if self.animator.state != PetState.WAVING:\n                self.animator.play(PetState.WAVING, loop=True, now=time.time())\n        elif dx < 0 and dy == 0:\n            if self.animator.state != PetState.HAPPY:\n                self.animator.play(PetState.HAPPY, loop=True, now=time.time())\n        elif dy < 0 and dx == 0:\n            if self.animator.state != PetState.SPEAKING:\n                self.animator.play(PetState.SPEAKING, loop=True, now=time.time())\n        elif dy > 0 and dx == 0:\n            if self.animator.state != PetState.SAD:\n                self.animator.play(PetState.SAD, loop=True, now=time.time())\n        elif dx != 0 and dy != 0:\n            if self.animator.state != PetState.BUSY:\n                self.animator.play(PetState.BUSY, loop=True, now=time.time())\n',
    '    def _update_move_animation(self, dx: int, dy: int) -> None:\n        if self._sleeping or self._dragged:\n            return\n        state = self._motion_state(dx, dy)\n        if self.animator.state != state:\n            self.animator.play(state, loop=True, now=time.time())\n\n    def _motion_state(self, dx: int, dy: int) -> PetState:\n        if dx > 0 and dy == 0:\n            return PetState.MOVING_RIGHT\n        if dx < 0 and dy == 0:\n            return PetState.MOVING_LEFT\n        if dy < 0 and dx == 0:\n            return PetState.MOVING_UP\n        if dy > 0 and dx == 0:\n            return PetState.MOVING_DOWN\n        if dx > 0 and dy < 0:\n            return PetState.MOVING_RIGHT\n        if dx < 0 and dy < 0:\n            return PetState.MOVING_LEFT\n        if dx > 0 and dy > 0:\n            return PetState.MOVING_RIGHT\n        if dx < 0 and dy > 0:\n            return PetState.MOVING_LEFT\n        if dx > 0:\n            return PetState.MOVING_RIGHT\n        if dx < 0:\n            return PetState.MOVING_LEFT\n        if dy > 0:\n            return PetState.MOVING_DOWN\n        return PetState.MOVING_UP\n\n    def _ensure_selected(self, now: float | None = None) -> None:\n        if not self._selected and not self._sleeping:\n            self._selected = True\n            if now is None:\n                now = time.time()\n            if self.animator.state != PetState.DRAG:\n                self.animator.play(PetState.IDLE, loop=True, now=now)\n'
)
app_path.write_text(app_text, encoding='utf-8')